### ISSUE TITLE
Telephant Trying to Read Posts Even When No Account Authorized

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#20]
When I first started Telephant, it immediately showed some errors in the terminal output. I hadn't had a chance to even begin typing my instance name for the authorization process, meaning Telephant doesn't distinguish whether or not it actually has authorization or even a site to go to before it tries to fetch posts.

The errors were about a dozen of the following:
`qrc:/qml/MessageView.qml:246: TypeError: Cannot read property 'x' of undefined`
where `'x'` is a bunch of various properties such as `'author'`, `'body'`, `'mediapreview'`, etc.

**Comment by creideiki** [comment]
Probably related, since it's also doing stuff without prerequisites being in place: If you start Telephant, then immediately close it, it writes a config file that looks like this:
```
Theme = "Material"
Style = "Dark"
FirstRun = false

[[Account]]
  Instance = ""
  ClientID = ""
  ClientSecret = ""
  Token = ""
```
Starting the application again then results in what looks like reads from uninitialized memory (my screenshot of which GitHub refuses to attach...): 512 posts, 25769803777 follows, 4658452646003212000 followers.

**Comment by muesli** [comment]
@creideiki Not quite related, but at least that part is fixed in master now. Thanks for the heads up!

**Comment by muesli** [comment]
Delayed / lazy component creation is now in master. Fixed.
