### ISSUE TITLE
Impossible to select text from posts.

### ISSUE THREAD

**Issue by Jzarecta** [muesli/telephant#54]
I cant seem to be able to select text, not in pane mode nor in selected post mode. Any reason for this?

**Comment by bionade24** [comment]
This annoyed me a lot, too. Thought it's wanted somehow.

**Comment by MasterOfTheTiger** [comment]
What is the root of this issue?

**Comment by muesli** [comment]
I made it selectable now. The problem is that it's not easy to handle both selection and click events, like the web interface currently does. Making it work would be an ugly hack, so for now I made the text selectable, but opening a post is only triggered by clicking on the post's timestamp for now.
